const surahId = [
  { "name": "Al-Fatihah",
    "id": 1 },
  { "name":"Al-Baqarah",
    "id": 2 },
  { "name":"Aali Imran",
    "id": 3 },
  { "name":"An-Nisa",
    "id": 4 },
  { "name":"Al-Maidah",
    "id": 5 },
  { "name":"Al-Anaam",
    "id": 6 },
  { "name":"Al-Araf",
    "id": 7 },
  { "name":"Al-Anfal",
    "id": 8 },
  { "name":"At-Taubah",
    "id": 9 },
  { "name":"Yunus",
    "id": 10 },
  { "name":"Hud",
    "id": 11 },
  { "name":"Yusuf",
    "id": 12 },
  { "name":"Ar-Rad",
    "id": 13 },
  { "name":"Ibrahim",
    "id": 14 },
  { "name":"Al-Hijr",
    "id": 15 },
  { "name":"An-Nahl",
    "id": 16 },
  { "name":"Al-Isra",
    "id": 17 },
  { "name":"Al-Kahf",
    "id": 18 },
  { "name":"Maryam",
    "id": 19 },
  { "name":"Ta-Ha",
    "id": 20 },
  { "name":"Al-Anbiya",
    "id": 21 },
  { "name":"Al-Haj",
    "id": 22 },
  { "name":"Al-Muminun",
    "id": 23 },
  { "name":"An-Nur",
    "id": 24 },
  { "name":"Al-Furqan",
    "id": 25 },
  { "name":"Ash-Shuara",
    "id": 26 },
  { "name":"An-Naml",
    "id": 27 },
  { "name":"Al-Qasas",
    "id": 28 },
  { "name":"Al-Ankabut",
    "id": 29 },
  { "name":"Ar-Rum",
    "id": 30 },
  { "name":"Luqman",
    "id": 31 },
  { "name":"As-Sajdah",
    "id": 32 },
  { "name":"Al-Ahzab",
    "id": 33 },
  { "name":"Saba",
    "id": 34 },
  { "name":"Al-Fatir",
    "id": 35 },
  { "name":"Ya-Sin",
    "id": 36 },
  { "name":"As-Saffah",
    "id": 37 },
  { "name":"Sad",
    "id": 38 },
  { "name":"Al-Az-Zumar",
    "id": 39 },
  { "name":"Ghafar",
    "id": 40 },
  { "name":"Fusilat",
    "id": 41 },
  { "name":"Ash-Shura",
    "id": 42 },
  { "name":"Az-Zukhruf",
    "id": 43 },
  { "name":"Ad-Dukhan",
    "id": 44 },
  { "name":"Al-Jathiyah",
    "id": 45 },
  { "name":"Al-Ahqaf",
    "id": 46 },
  { "name":"Muhammad",
    "id": 47 },
  { "name":"Al-Fath",
    "id": 48 },
  { "name":"Al-Hujurat",
    "id": 49 },
  { "name":"Qaf",
    "id": 50 },
  { "name":"Adz-Dzariyah",
    "id": 51 },
  { "name":"At-Tur",
    "id": 52 },
  { "name":"An-Najm",
    "id": 53 },
  { "name":"Al-Qamar",
    "id": 54 },
  { "name":"Ar-Rahman",
    "id": 55 },
  { "name":"Al-Waqiah",
    "id": 56 },
  { "name":"Al-Hadid",
    "id": 57 },
  { "name":"Al-Mujadilah",
    "id": 58 },
  { "name":"Al-Hashr",
    "id": 59 },
  { "name":"Al-Mumtahanah",
    "id": 60 },
  { "name":"As-Saf",
    "id": 61 },
  { "name":"Al-Jumah",
    "id": 62 },
  { "name":"Al-Munafiqun",
    "id": 63 },
  { "name":"At-Taghabun",
    "id": 64 },
  { "name":"At-Talaq",
    "id": 65 },
  { "name":"At-Tahrim",
    "id": 66 },
  { "name":"Al-Mulk",
    "id": 67 },
  { "name":"Al-Qalam",
    "id": 68 },
  { "name":"Al-Haqqah",
    "id": 69 },
  { "name":"Al-Maarij",
    "id": 70 },
  { "name":"Nuh",
    "id": 71 },
  { "name":"Al-Jinn",
    "id": 72 },
  { "name":"Al-Muzammil",
    "id": 73 },
  { "name":"Al-Mudaththir",
    "id": 74 },
  { "name":"Al-Qiyamah",
    "id": 75 },
  { "name":"Al-Insan",
    "id": 76 },
  { "name":"Al-Mursalat",
    "id": 77 },
  { "name":"An-Naba",
    "id": 78 },
  { "name":"An-Naziat",
    "id": 79 },
  { "name":"Abasa",
    "id": 80 },
  { "name":"At-Takwir",
    "id": 81 },
  { "name":"Al-Infitar",
    "id": 82 },
  { "name":"Al-Mutaffifin",
    "id": 83 },
  { "name":"Al-Inshiqaq",
    "id": 84 },
  { "name":"Al-Buruj",
    "id": 85 },
  { "name":"At-Tariq",
    "id": 86 },
  { "name":"Al-Ala",
    "id": 87 },
  { "name":"Al-Ghashiyah",
    "id": 88 },
  { "name":"Al-Fajr",
    "id": 89 },
  { "name":"Al-Balad",
    "id": 90 },
  { "name":"Ash-Shams",
    "id": 91 },
  { "name":"Al-Layl",
    "id": 92 },
  { "name":"Adh-Dhuha",
    "id": 93 },
  { "name":"Al-Inshirah",
    "name": 94 },
  { "name":"At-Tin",
    "id": 95 },
  { "name":"Al-Alaq",
    "id": 96 },
  { "name":"Al-Qadar",
    "id": 97 },
  { "name":"Al-Bayinah",
    "id": 98 },
  { "name":"Az-Zalzalah",
    "id": 99 },
  { "name":"Al-Adiyah",
    "id": 100 },
  { "name":"Al-Qariah",
    "id": 101 },
  { "name":"At-Takathur",
    "id": 102 },
  { "name":"Al-Asr",
    "id": 103 },
  { "name":"Al-Humazah",
    "id": 104 },
  { "name":"Al-Fil",
    "id": 105 },
  { "name":"Quraish",
    "id": 106 },
  { "name":"Al-Maun",
    "id": 107 },
  { "name":"Al-Kauthar",
    "id": 108 },
  { "name":"Al-Kafirun",
    "id": 109 },
  { "name":"An-Nasr",
    "id": 110 },
  { "name":"Al-Masad",
    "id": 111 },
  { "name":"Al-Ikhlas",
    "id": 112 },
  { "name":"Al-Falaq",
    "id": 113 },
  { "name":"An-Nas",
    "id": 114 },
];
export default surahId;
